### ISSUE TITLE
MarkdownCompositeNative & MarkdownColumnNative

### ISSUE THREAD

**Issue by miteshashar** [hasgeek/funnel#1495]
`MarkdownCompositeNative` & `MarkdownColumnNative` created in #1485 will evolve through the following stages during our ongoing markdown transition.

### Stage 1: Introduce `_tokens`
- [ ] `_text`, `_html` -> `_text`, `_html`, `_tokens`
  The `_tokens` column can be introduced once the functionality of `markdown()` to return a a token stream is done.

### Stage 2: Remove `_html`
The `_html` column can be removed once the below tasks are done.
- [ ] All models using `MarkdownColumn` have been moved to `MarkdownColumnNative` (optional, but ideal)
- [ ] The front-end is capable of rendering HTML from markdown-it's token stream everywhere.

### Stage 3: Introducing the `_hash` column (Lower prority)
- [ ] `_text`, `_tokens`, `_hash`
  After `_tokens` have been incorporated in UI and are stable in all their touchpoints, we can make this move when we want to switch later for [`vector_search`](https://github.com/hasgeek/funnel/blob/3bc1c43642e25eab93a82ac94949a10c9d4d7108/funnel/models/update.py#L166-L180).
  `_hash` will be the redis cache hash to be derived using SHA256 or Blake2b.
  Removing `_html` means the `search_vector` will be based on `_text` column, where it will pick up directives like `\`\`\`python` or `\`\`\`mermaid` as actual words in text, which is not ok since it is misrepresentative.
  Search vector should have content words, not directives. Whether token stream or source text, those directives should be stripped — ideally.

**Comment by jace** [comment]
I think stage 2 and 3 should be reversed: that is, introduce `_hash` and switch to cached on-demand server-side rendering first, retaining the statically rendered `_html` for Postgres search. Client-side rendering (outside of preview) and Postgres indexing become separate stages.

Client-side rendering is iffy because of embeds — the embed preview will have to be fetched client-side, or a new API endpoint will have to make server-side previews, at risk of being misused as a proxy and therefore needing further lockdowns.
