### ISSUE TITLE
Create site status tracker

### ISSUE THREAD

**Issue by jace** [hasgeek/funnel#491]
We have periodic outages from unexpected quarters. As our site transforms into an app that others depend on, having a status dashboard is critical. There's a long ignored dashboard at status.hasgeek.com running on Google App Engine (so it's isolated from our hosting).

* [ ] Revisit statusboard to see if it's still a good choice.
* [ ] Pick a safe place to host it (GAE or elsewhere).
* [ ] Update the software.
* [ ] Update the tests to cover all UWSGI apps on an automated basis (per minute/five minutes).
* [ ] Include a link to OONI Run and services like "down for me or everyone else" to help users determine if the problem is at their end.

**Comment by jace** [comment]
This is now outsourced to UptimeRobot at status.hasgeek.com. Influxdb and Grafana are used for internal monitoring.
